package:
  name: funnyplotting
  version: 1.0

source:
  git_rev: v1.0
  git_url: https://github.com/hroney/funnyplotting.git

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - wxpython


test:
  imports:
    - funnyplotting

about:
  home: https://github.com/hroney/funnyplotting
  license: GPL3
  license_file: LICENSE
  description: 'This package allows you to plot the 2D/3D graph for a given function'